question_data = [
    {
        "category": "Science: Computers",
        "type": "multiple",
        "difficulty": "easy",
        "question": "What does GHz stand for?",
        "correct_answer": "Gigahertz",
        "incorrect_answers": ["Gigahotz", "Gigahetz", "Gigahatz"],
    },
    {
        "category": "Science: Computers",
        "type": "multiple",
        "difficulty": "easy",
        "question": "HTML is what type of language?",
        "correct_answer": "Markup Language",
        "incorrect_answers": [
            "Macro Language",
            "Programming Language",
            "Scripting Language",
        ],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "multiple",
        "difficulty": "easy",
        "question": "What does the Prt Sc button do?",
        "correct_answer": "Captures what&#039;s on the screen and copies it to your clipboard",
        "incorrect_answers": [
            "Nothing",
            "Saves a .png file of what&#039;s on the screen in your screenshots folder in photos",
            "Closes all windows",
        ],
    },
    {
        "category": "Science: Computers",
        "type": "multiple",
        "difficulty": "easy",
        "question": "What is the code name for the mobile operating system Android 7.0?",
        "correct_answer": "Nougat",
        "incorrect_answers": ["Ice Cream Sandwich", "Jelly Bean", "Marshmallow"],
    },
    {
        "category": "Science: Computers",
        "type": "multiple",
        "difficulty": "easy",
        "question": "On Twitter, what was the original character limit for a Tweet?",
        "correct_answer": "140",
        "incorrect_answers": ["120", "160", "100"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Time on Computers is measured via the EPOX System.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "multiple",
        "difficulty": "easy",
        "question": "How long is an IPv6 address?",
        "correct_answer": "128 bits",
        "incorrect_answers": ["32 bits", "64 bits", "128 bytes"],
    },
    {
        "category": "Science: Computers",
        "type": "multiple",
        "difficulty": "easy",
        "question": "What language does Node.js use?",
        "correct_answer": "JavaScript",
        "incorrect_answers": ["Java", "Java Source", "Joomla Source Code"],
    },
]
